### ISSUE TITLE
Sick_generic_caller

### ISSUE THREAD

**Issue by schleptech** [SICKAG/sick_scan#102]
Getting attached error![image](https://user-images.githubusercontent.com/71199728/93102096-b7e17e80-f670-11ea-88ad-946738419631.png)

**Comment by michael1309** [comment]
We have seen that you build the ROS node under Raspberry-Pi. This platform is not officially supported by us. But it seems that the ROS system does not start correctly. You can try to start roscore once in a separate thread and then run the launch command again.

In addition (or as an alternative) you can try to start `sick_generic_caller` directly. The roslaunch command will in detail start a process with argument like this:
```
sick_generic_caller __name:=sick_lms_1xxx __log:=/tmp/debuglog.log
```
You could check this by using the `ps -afx|grep sick_generic_caller`.

Also you must source the project ros environment by 
using a command sequence like this:
```
cd ~/ros_catkin_ws
source ./devel/setup.bash
```
Otherwise the launch command cannot find `sick_generic_caller`.

Best regards,
Michael

**Comment by schleptech** [comment]
Thanks for your response, Michael.

I will give that a try this evening to see. What platforms do you officially support? If that doesn’t work, I will start over with clean slate from one of your recommended platforms. Ubuntu?

On Sep 14, 2020, at 12:58 PM, Michael Lehning <notifications@github.com> wrote:

﻿

We have seen that you build the ROS node under Raspberry-Pi. This platform is not officially supported by us. But it seems that the ROS system does not start correctly. You can try to start roscore once in a separate thread and then run the launch command again.

In addition (or as an alternative) you can try to start sick_generic_caller directly. The roslaunch command will in detail start a process with argument like this:

sick_generic_caller __name:=sick_lms_1xxx __log:=/tmp/debuglog.log


You could check this by using the ps -afx|grep sick_generic_caller.

Also you must source the project ros environment by
using a command sequence like this:

cd ~/ros_catkin_ws
source ./devel/setup.bash


Otherwise the launch command cannot find sick_generic_caller.

Best regards,
Michael

**Comment by michael1309** [comment]
The default support is for Ubuntu x86 systems.
