### ISSUE TITLE
Detect loss of comms and restart communication

### ISSUE THREAD

**Issue by srsidd** [SICKAG/sick_scan#114]
Hi I've a Sick MRS6000 lidar I'm using. The driver works great out of the box and haven't had any issue gathering point cloud data. 

However I noticed that when running the driver, if we lose power to the lidar, the driver doesn't detect a loss of communication with the device, furthermore when the device is switched back on and is back to operational state, the driver doesn't try to re-establish communication with the sensor and just stays there.

Is there anyway to overcome this issue?

**Comment by michael1309** [comment]
The MRS6000 resumes transmission when the network connection is interrupted. However, if the complete MRS6xxx is shut down, no reboot is currently performed. The driver of the MRS6xxx basically shows the communication with the MRS6xxx. For a complete monitoring with if necessary restart of the process we recommend you to make your own implementation, e.g. by checking the accessibility of the IP address by other tools, in order to control the process from the outside and if necessary restart the driver. A fully automatic monitoring within the driver is currently not provided.
