### ISSUE TITLE
SICK LMS5** reports an error during use 

### ISSUE THREAD

**Issue by zhshwind** [SICKAG/sick_scan#141]
SICK LMS5** The following error occurred during the test using sick_scan; 

Errors are reported more frequently when two lidars are connected at the same time. How can this problem be solved? 

![使用中问题1](https://user-images.githubusercontent.com/67258649/131218876-7b56a84e-18bf-4340-a9ea-b89f6410038a.png)
![使用中问题2](https://user-images.githubusercontent.com/67258649/131218878-fff188a0-741a-4e39-ad3c-ee0074c9161e.png)
![使用中问题3](https://user-images.githubusercontent.com/67258649/131218880-679c58ad-ef5d-4d16-aed6-ddac318c662c.png)
![使用中问题4](https://user-images.githubusercontent.com/67258649/131218882-6a8d6afd-26d9-4a06-a219-e1bade19a90d.png)
![使用中问题5](https://user-images.githubusercontent.com/67258649/131218886-f5740068-0c81-4b32-abdb-d46c76dbf498.png)
![微信截图_20210824141327](https://user-images.githubusercontent.com/67258649/131218887-d5424d0b-853c-4adf-9bb1-54ef471a3a75.png)

**Comment by zhshwind** [comment]
Hello：
    The problem we are encountering at present is: every time after power on, the lidar ros node will report an error.
    Most of the time the error is TCP Time_out. This kind of error, the lidar data can be read normally.
    Another type of error-reporting lidar cannot be used normally. The error message is shown in the figure below.




    We don't know how this problem arose and how it needs to be solved. Hope to get your professional guidance. 
    Thanks!

    





|
郑爽
***@***.***
|
签名由网易邮箱大师定制
On 9/2/2021 16:48，Michael ***@***.***> wrote：

Hello ,

Unfortunately I was not able to reproduce the error.
You use the field evaluation or? How is it configured ?
Does the error occur immediately after the start (so it looks in the logs)?

Which variant of the software do you use? Try the latest version from this repo.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rostest** [comment]
Hello,

thanks for your report. I can't see the figure, but it looks like the lidar is starting in COLA-Ascii mode after cold start, while the driver is expecting the COLA-Binary mode. In this case, a timeout can occure due to protocol switching.

Using COLA-Binary communication is recommended. Please make sure to set the lidar permanently to COLA-Binary. You can do this by using SOPAS ET after login to "authorized client" level. After switching you should save the parameter to the internal memory of the scanner (EEPROM). After a new cold start, check in SOPAS ET that the setting is actually stored in the lidar .

You can find additional information in the closed issues #130 and #6.

**Comment by rostest** [comment]
Closed due to inactivity.

**Comment by zhshwind** [comment]
Hello：
    Thank you for your response.

    The problem we are currently encountering should not be the reason you mentioned.
    I checked the current settings, the current lidar permanently is COLA-Binary. 
|
郑爽
***@***.***
|
签名由网易邮箱大师定制
On 9/20/2021 ***@***.***> wrote：

Closed #141.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
