### ISSUE TITLE
No echo selection support for LMS511

### ISSUE THREAD

**Issue by themightyoarfish** [SICKAG/sick_scan#150]
I can enable first, all, or last echo with `filter_echos` parameter for the MRS6xxx. The same setting has no effect on LMS511, which should give me 5 echos.
It seems this setting is only accepted for multilayer scanners: https://github.com/SICKAG/sick_scan/blob/c4e03eee441a0753c0bed5af155b1e4922b8de01/driver/src/sick_scan_common.cpp#L2316

This is a bummer since the 5 echos are one of the main selling points for this model.
Can this be enabled?

**Comment by michael1309** [comment]
We scheduled this for next by using the driver under the repo. sick_scan_xd 

see https://github.com/SICKAG/sick_scan_xd for details.

**Comment by michael1309** [comment]
this issue was fixed in the devel branch with in the  sick_scan_xd repo with commit 
https://github.com/SICKAG/sick_scan_xd/commit/34c7abd7fa0cd1f8795f993caddeb42d4db560f7
you can either use this repo (it's recomended to use sick_scan-xd in the future) or apply the patch to your sick_scan source code
