### ISSUE TITLE
TCP timing out, help?

### ISSUE THREAD

**Issue by Alexandre-Caldeira** [SICKAG/sick_scan#152]
Using the [Troubleshooting Guide](https://github.com/SICKAG/sick_scan/blob/master/doc/ipconfig/ipconfig.md), I tried to start a TCP connection with a SICK LMS111, having already set a static IP (in SOPAS Tool in Windows), when I do:

```
nc -z -v -w5 169.254.0.2 2112
```

I get:

```
nc: connect to 169.254.0.2 port 2112 (tcp) timed out: Operation now in progress
```

I have honestly no idea what is wrong, I have tried multiple ROS packages, distros, even changed Linux distros but nothing seems to point to the issue nor solve it. 

Any suggestions?
Any other troubleshooting tips?

PS.: I have tried to set the ip to something like 198.168.XX.XXX but SOPAS won't allow it, unless it's something like 169.254.XX.XXX (but I don't think that's related to nor the actual issue here).

**Comment by michael1309** [comment]
I guess, that you are using DHCP. We strongly recommend to use a static IP setup. For this you have to switch from DHCP to static.
Please ask you sys admin for details. Also check for 192.168.xxx.xxx instead of 198.168.xxx.xxx. Also it is a good idea for a local connection between your PC and the lidar to use a separate ethernet interface (e.g. USB/Ethernet-adapter). There you can establish your own subnet.

**Comment by michael1309** [comment]
Close due to inactivity.
