### ISSUE TITLE
The timelimit in the launch file does not take effect

### ISSUE THREAD

**Issue by FlyHan** [SICKAG/sick_scan#160]
The timeout is determined by const(timeout = 30000), but it has nothing to do with timelimit

sick_scan_common_tcp.cpp: 
```
int SickScanCommonTcp::get_datagram(ros::Time &recvTimeStamp, unsigned char *receiveBuffer, int bufferSize,
                                      int *actual_length,
                                      bool isBinaryProtocol, int *numberOfRemainingFifoEntries)
    ...  
     /*
     * Write a SOPAS variable read request to the device.
     */
    std::vector<unsigned char> reply;

    // Wait at most 5000ms for a new scan
    size_t timeout = 30000;
    bool exception_occured = false;

    char *buffer = reinterpret_cast<char *>(receiveBuffer);

    if (readWithTimeout(timeout, buffer, bufferSize, actual_length, &exception_occured, isBinaryProtocol) !=
        ExitSuccess)
    ...
```

**Comment by rostest** [comment]
We recommend to use [sick_scan_xd](https://github.com/SICKAG/sick_scan_xd) for further development. 
Regarding the issue, there are two different timelimits:
* the const timeout of 30 seconds is required, since a lidar response may take up to 30 seconds, and
* the timelimit configured in the launchfile is used as max. timeout during startup (max. timeout for a sopas response).
