### ISSUE TITLE
No data being published to /scan topic using sick_mrs_6xxx.launch MRS6124

### ISSUE THREAD

**Issue by GrantDare** [SICKAG/sick_scan#23]
I am using this package with the MRS6124 and thePointcloud2 data is publishing correctly but using the launch file sick_mrs_6xxx.launch (I changed the IP to my IP) the /scan topic doesn't publish any data? Is this a configuration setting I need to set or is there an extra parameter I need to use? I understand Pointcloud2 data is more accurate though I require the sensor_msgs/LaserScan data for the slam_gmapping package.

**Comment by michael1309** [comment]
Hello, GrantDare,

the individual layers of the laser scanner are not planar except for the 0° plane due to the operating principle of the scanner. For "sensor_msgs/LaserScan" the planarity is absolutely necessary, therefore the individual planes are not published as "LaserScan". With some effort you can interpolate planes from the pointCloud2 data. From our point of view it would be better to use a slam package which supports PointCloud2 data like Google Cathographer (https://google-cartographer-ros.readthedocs.io/en/latest/).

Best regards, Michael
