### ISSUE TITLE
Error during launching process (LMS1104C)

### ISSUE THREAD

**Issue by pid0501r** [SICKAG/sick_scan#29]
Dear Michael,

I cannot launch LMS1104c and get error message as picture in attachment.
![error message](https://user-images.githubusercontent.com/46316188/50677286-fa496000-1033-11e9-8ad8-ffc3e2071465.JPG)
(Driver of LMS5xx works well so I think it means I use correct procedure to launch it)

Is there any further setting steps we missed? 

I list information of LMS we use below.
model name: LMS1104C-111031S01
firmware version: 1.4.0.0R

Furthemore, I notice that driver status is "stable" but comment in launch file "lms1xxx" is "FOR FUTURE USE. NOT SUPPORTED NOW." . Is the driver still not available?

Please let me know if you need further information.

Sincerely Yours
pid0501r

**Comment by michael1309** [comment]
Dear pid0501r,

I checked these issues. My LMS shows the same error code for the command sWN LMDScanDataCfg. I will fix this until mid-January. You should still work with the driver if you use the default settings for the angle ranges and echoes. We had started the driver development before the scanner was available as a serial product. That's why it's still "experimental". We will also change that in January.

Best regards,
Michael
